[package]
name = "plonk_prototype"
version = "0.1.0"
authors = []
edition = "2018"
readme = "README.md"
repository = "https://github.com/Manta-Network/Plonk-Prototype"
keywords = ["cryptography", "circuits", "zk-snarks", "zero-knowledge", "crypto"]
categories =["algorithms", "cryptography", "science"]
description = "An implementation of various circuits within Manta Network"
license = "MPL-2.0"
exclude = [
    ".gitignore",
    "Cargo.lock",
    ".github/"
]

[dependencies]
num = "0.3"
fast-math = "0.1"

rand_chacha = "0.2.2"
rand = "0.7.3"
rand_xorshift = { version = "0.2" }
blake2 = { version = "0.8", default-features = false }
sha2 = "0.9.1"
merkle = "1.11"
ring = "0.16.15"
tracing = { version = "0.1", default-features = false, optional = true }
tracing-subscriber = { version = "0.2", default-features = false, optional = true }

ark-std = "0.3.0"
ark-ff = "0.3.0"
ark-bls12-381 = "0.3.0"
ark-r1cs-std = "0.3.1"
ark-groth16 = "0.3.0"


[dev-dependencies]
criterion = "0.3"